# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Arabic spellchecker"
ar = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Arabic, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
ar = "TRANSLATE: A spellchecker for Arabic, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ar"

[windows]
system_product_code = "{8CAC7F22-5E19-4EBF-9C0E-7E4B77CE9639}_is1"
legacy_product_codes = [
    { value = "07F65A41-7800-41CD-92BC-7CE3927C6F8F", kind = "nsis" },
    { value = "4C98BD40-0248-4314-B820-0712CB4AF0B3", kind = "nsis" }
]

[package.speller]
name = "Arabic"
version = "0.1.1"

[package.grammar]
name = "Arabic"
version = "0.1.0"

[package.tts-textproc]
name = "Arabic"
version = "0.1.0"

[package.hyphenator]
name = "Arabic"
version = "0.1.0"
